# Allows Egress to Token Vault and PSP
# Allows Ingress from Ingress Gateway
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: payment-api-allow
  namespace: cde-production
spec:
  podSelector:
    matchLabels:
      app: payment-authorization-api
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app: ingress-gateway

  egress:
    - to:
        - podSelector:
            matchLabels:
              app: token-vault-service
      ports:
        - port: 8080
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: psp-connector
      ports:
        - port: 8080
          protocol: TCP